inherit_gem:
  rubocop-config-captive:
    - config/default.yml

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/db/schema.rb'
    - node_modules/**/*
    - '**/config/puma.rb'

Layout/LineLength:
  Exclude:
    - '**/*.gemspec'
