source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in captive-authentication.gemspec.
gemspec

gem "puma", "6.3.0"

gem "sqlite3", "1.6.3"

gem "sprockets-rails", "3.4.2"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
