default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: captive-sdk_development

test:
  <<: *default
  database: captive-sdk_test

production:
  <<: *default
  database: captive-sdk_production
  username: captive-sdk
  password: <%= ENV["CAPTIVE_AUTHENTICATION_DATABASE_PASSWORD"] %>
