source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in captive-crash-reporter.gemspec.
gemspec

gem "puma", "7.0.4"

gem "sqlite3", "1.7.3"

gem "sprockets-rails", "3.5.2"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
