name: Ruby Gem

on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        gem_folder: [., captive-admin, captive-api, captive-theme]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7

      - name: Publish to RubyGems
        run: |
          cd ${{ matrix.gem_folder }}
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
          cd ..
        env:
          GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_AUTH_TOKEN }}'

      - name: Publish to GPR
        run: |
          cd ${{ matrix.gem_folder }}
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
          cd ..
        env:
          GEM_HOST_API_KEY: 'Bearer ${{ secrets.GITHUB_TOKEN }}'
